export const MERCHANT_LOGIN_REQUEST = 'MERCHANT_LOGIN_REQUEST';
export const MERCHANT_LOGIN_SUCCESS = 'MERCHANT_LOGIN_SUCCESS';
export const MERCHANT_LOGIN_FAIL = 'MERCHANT_LOGIN_FAIL';
export const MERCHANT_LOGOUT = 'MERCHANT_LOGOUT';

export const MERCHANT_REGISTER_REQUEST = 'MERCHANT_REGISTER_REQUEST';
export const MERCHANT_REGISTER_SUCCESS = 'MERCHANT_REGISTER_SUCCESS';
export const MERCHANT_REGISTER_FAIL = 'MERCHANT_REGISTER_FAIL';

export const MERCHANT_DETAILS_REQUEST = 'MERCHANT_DETAILS_REQUEST';
export const MERCHANT_DETAILS_SUCCESS = 'MERCHANT_DETAILS_SUCCESS';
export const MERCHANT_DETAILS_FAIL = 'MERCHANT_DETAILS_FAIL';
export const MERCHANT_DETAILS_RESET = 'MERCHANT_DETAILS_RESET';

export const MERCHANT_UPDATE_PROFILE_REQUEST = 'MERCHANT_UPDATE_PROFILE_REQUEST';
export const MERCHANT_UPDATE_PROFILE_SUCCESS = 'MERCHANT_UPDATE_PROFILE_SUCCESS';
export const MERCHANT_UPDATE_PROFILE_FAIL = 'MERCHANT_UPDATE_PROFILE_FAIL';
export const MERCHANT_UPDATE_PROFILE_RESET = 'MERCHANT_UPDATE_PROFILE_RESET';

export const MERCHANT_LIST_REQUEST = 'MERCHANT_LIST_REQUEST';
export const MERCHANT_LIST_SUCCESS = 'MERCHANT_LIST_SUCCESS';
export const MERCHANT_LIST_FAIL = 'MERCHANT_LIST_FAIL';
export const MERCHANT_LIST_RESET = 'MERCHANT_LIST_RESET';

export const MERCHANT_DELETE_REQUEST = 'MERCHANT_DELETE_REQUEST';
export const MERCHANT_DELETE_SUCCESS = 'MERCHANT_DELETE_SUCCESS';
export const MERCHANT_DELETE_FAIL = 'MERCHANT_DELETE_FAIL';

export const MERCHANT_UPDATE_REQUEST = 'MERCHANT_UPDATE_REQUEST';
export const MERCHANT_UPDATE_SUCCESS = 'MERCHANT_UPDATE_SUCCESS';
export const MERCHANT_UPDATE_FAIL = 'MERCHANT_UPDATE_FAIL';
export const MERCHANT_UPDATE_RESET = 'MERCHANT_UPDATE_RESET';
