export const PAY_MERCHANT_SUBSCRIPTION_FEE_REQUEST =
  'PAY_MERCHANT_SUBSCRIPTION_FEE_REQUEST';
export const PAY_MERCHANT_SUBSCRIPTION_FEE_SUCCESSFUL =
  'PAY_MERCHANT_SUBSCRIPTION_FEE_SUCCESSFUL';
export const PAY_MERCHANT_SUBSCRIPTION_FEE_FAILED =
  'PAY_MERCHANT_SUBSCRIPTION_FEE_FAILED';
export const RAVE_CONNECTION_SUCCESSFUL = 'RAVE_CONNECTION_SUCCESSFUL';
export const RAVE_CONNECTION_REQUEST = 'RAVE_CONNECTION_REQUEST';
export const RAVE_CONNECTION_REQUEST_FAILED =
  'RAVE_CONNECTION_REQUEST_FAILED';
